import {
    TeamRutherford,
    TeamTunde,
    TeamEtenikang,
    TeamObinna,
    TeamOyakhire,
    TeamBen,
    TeamAdeshina,
    TeamEliko,
    TeamMohammad,
    TeamDapo,

    AdviserMar,
    AdviserCosti,
} from '../../../assets/images';

export const teamList = [
    {
        name: 'Rutherford Atayobo',
        image: TeamRutherford,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Rutherford Atayobo',
        image: TeamTunde,
        position: 'CTO/Lead Backend Developer',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Etenikang David',
        image: TeamEtenikang,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Obinna Inya A.',
        image: TeamObinna,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Oyakhire Emmanuel',
        image: TeamOyakhire,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Obot Ubong Benjamin',
        image: TeamBen,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Adeshina Olarewaju',
        image: TeamAdeshina,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Eliko Blessing',
        image: TeamEliko,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Muhammad Nazif',
        image: TeamMohammad,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Dapo Paul Ogunlana',
        image: TeamDapo,
        position: 'CEO',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
];


export const advisorList = [
    {
        name: 'Maruoane Fikri',
        image: AdviserMar,
        position: 'CEO Sinverse',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
    {
        name: 'Constantine Ene',
        image: AdviserCosti,
        position: 'CEO Vanilla Network Metaverse',
        linkedIn: 'linkedin',
        faceBook: 'facebook',
        twitter: 'twitter',
    },
];