 
 
 export const routeConstants = {
     all: '*',
     home: '/',
     about: 'about',
     userLogin: 'log-in',
     register: 'register',
     privacyPolicy: 'privacy-policy',
     terms: 'terms',
     amlPolicy: 'aml-policy',
     faq: 'faq',
     industryNews: 'news',
     help: 'help',
     learn: 'learn',
     productUpdates: 'product-updates',
     careers: 'careers',
     contact: 'contact-us',
     operators: 'operators',
     placeHolder: 'waiting',
     cryptoCurrencies: 'crypto-currencies',
     manillaCard: 'card',
     manillaToken: 'token',

     admin: 'admin',
     dashboard: 'dashboard',
     adminRegister: 'register',
     adminLogin: 'log-in',
     adminStatistics: 'stats',
     adminPosts: 'posts',
     adminWaitlistMessages: 'waitlist-messages',
     adminVisitorMessages: 'visitor-messages',
 };